mysite/urls.py
from django.urls import path
from . import views

app_name = 'mysite'
urlpatterns = [
    path('', views.home, name="home"),
    path('contact/', views.contact, name="contact"),
    path('about/', views.about, name="about"),
    path('skills/', views.skills, name="skills"),
    path('portfolio/', views.portfolio, name="portfolio"),
    path('services/', views.services, name="services"),


]

portf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from django.views.generic import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('mysite.urls', namespace="mysite")),

]


if settings.DEBUG:

    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

mysite/models.py
from django.db import models

# Create your models here.


class Project(models.Model):
    title = models.CharField(max_length=200)
    github_link = models.URLField()
    description = models.TextField()
    thumbnail = models.ImageField(null=True)
    live = models.URLField(blank=True, null=True)
    tech = models.CharField(max_length=200, null=True)

    def __str__(self):
        return "{0}".format(self.title)


class Message(models.Model):
    name = models.CharField(max_length=200)
    address = models.CharField(max_length=200)
    body = models.TextField()
    budget = models.IntegerField()

    def __str__(self):
        return "{0} from {1}".format(self.name, self.address)

mysite/views.py
from django.shortcuts import render
from .models import Project, Message
# Create your views here.


def home(request):
    context = {
    }
    return render(request, "index.html", context)


def contact(request):
    context = {
    }
    return render(request, "contact.html", context)


def services(request):
    context = {
    }
    return render(request, "services.html", context)


def portfolio(request):
    projects = Project.objects.all()
    context = {
        'projects': projects
    }
    return render(request, "portfolio.html", context)


def skills(request):
    context = {
    }
    return render(request, "skills.html", context)


def about(request):
    context = {
    }
    return render(request, "about.html", context)

mysite/templates/about.html
<!--Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
{% load static %}

<!DOCTYPE html>
<html lang="zxx">

{% include "include/head.html" %}


<body>
    <!-- inner banner -->
    <div class="inner-banner-agile">
        <!-- header -->
        {% include "include/top_nav.html" %}

        <!-- //header -->
    </div>
    <!-- inner banner -->
    <!-- about -->
    <section class="main-sec-w3 pb-sm-5 about-bot-w3l">
        <div class="container">
            <div class="wthree-inner-sec  about-bot-w3ls">
                <div class="sec-head">
                    <h1 class="sec-title-w3 text-capitalize">about me</h1>
                    <span class="block"></span>
                </div>
                <div class="about_w3l position-relative">
                    <div class="profile-wrapper">
                        <div class="profile-image">
                            <img src="{% static 'images/about.jpg' %}" alt="about _image" class="img-fluid" />
                        </div>
                        <h2 class="profile-title">Nahid
                            <span>Hassan</span>
                        </h2>
                        <div class="profile-info">
                            <div class="content">
                                <div class="row  pro-contact">
                                    <div class="col-4">
                                        <img src="{% static 'images/profile.jpg' %}" alt=""
                                            class="rounded-circle img-fluid">
                                    </div>
                                    <div class="col-sm-8  my-auto">
                                        <div class="link_about">
                                            <i class="fab fa-github" aria-hidden="true"></i>
                                            <a href="https://github.com/Nahid71" target="_blank">Github</a>
                                        </div>
                                        <div class="link_about my-2">
                                            <i class="fab fa-linkedin-in" aria-hidden="true"></i>
                                            <a href="https://www.linkedin.com/in/nahid1171" target="_blank">Linkdin</a>
                                        </div>
                                        <div class="link_about">
                                            <i class="fa fa-envelope" aria-hidden="true"></i>
                                            <a href="#">nahidjahid8698@gmail.com</a>
                                        </div>
                                    </div>
                                </div>
                                <p>
                                    <h5>#Full Stack Develper / #Web #Data Scientest & #Business Analyst.</h5> BCSE
                                    graduate
                                    offering a strong foundation in software engineering and programming principles
                                    across multiple platforms. Experienced in object-oriented programming; developing,
                                    testing and debugging code; designing interfaces; and administering systems and
                                    networks.Quickly learn and master new technologies; successful working in both team
                                    and self-directed settings.

                                </p>


                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- //about -->
    <!-- footer -->
    {% include "include/footer.html" %}
    <!-- //footer -->
    <!-- js -->
    <script src="{% static 'js/jquery-2.2.3.min.js' %}"></script>
    <!-- //js -->
    <!-- few java snippets-->
    <script src="{% static 'js/strive.js' %}"></script>
    <!-- //few java snippets-->
    <!-- nav -->
    <script src="{% static 'js/menuFullpage.min.js' %}"></script>
    <!-- //nav -->
    <!-- smooth scroll -->
    <script src="{% static 'js/SmoothScroll.min.js' %}"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/bootstrap.js' %}"></script>
</body>

</html>

mysite/templates/contact.html
<!--Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
{% load static %}
<!DOCTYPE html>
<html lang="zxx">

{% include "include/head.html" %}

<body>
    <!-- inner banner -->
    <div class="inner-banner-agile contact-bg">
        <!-- header -->
        {% include "include/top_nav.html" %}
        <!-- //header -->
    </div>
    <!-- //inner banner -->
    <!-- contact -->
    <section class="main-sec-w3 pb-5">
        <div class="container">
            <div class="wthree-inner-sec">
                <div class="sec-head">
                    <h1 class="sec-title-w3 text-capitalize">contact me</h1>
                    <span class="block"></span>
                </div>
                <div class="form-wrapper">
                    <form action="#" method="post">
                        <div class="d-flex flex-column">
                            <label>Your Name:</label>
                            <input class="text-input" type="text" name="text1" id="text1" required>
                        </div>
                        <div class="d-flex flex-column my-sm-5 my-3">
                            <label>Your Email Address:</label>
                            <input class="text-input" type="email" name="email" id="email" required>
                        </div>

                        <div class="d-flex flex-column my-sm-5 mt-3 mb-4">
                            <label>Your Budget: $
                                <span class="budget-text">300</span>
                            </label>
                            <input type="range" id="budget" min="0" value="300" max="1000" step="100" class="mt-3">
                        </div>
                        <div class="d-flex flex-column my-sm-5 my-3">
                            <div class="message">
                                <h2>Add Your Message</h2>
                            </div>
                            <textarea name="t1" id="t1" required></textarea>
                        </div>
                        <input class="submit" type="submit" value="Send">
                    </form>
                </div>
            </div>
        </div>
    </section>
    <!-- //contact -->
    <!-- footer -->
    {% include "include/footer.html" %}
    <!-- //footer -->
    <!-- js -->
    <script src="{% static 'js/jquery-2.2.3.min.js' %}"></script>
    <!-- //js -->
    <!-- few java snippets-->
    <script src="{% static 'js/strive.js' %}"></script>
    <!-- //few java snippets-->
    <!-- nav -->
    <script src="{% static 'js/menuFullpage.min.js' %}"></script>
    <!-- //nav -->
    <!-- smooth scroll -->
    <script src="{% static 'js/SmoothScroll.min.js' %}"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/bootstrap.js' %}"></script>

</body>

</html>

mysite/templates/home.html
<html>

<body>
    <p>hi </p>
</body>

</html>

mysite/templates/include/footer.html
{% load staticfiles %}
{% load static %}
<footer>
  <div class="cpy-right text-center py-4">
    <p class="text-white">© 2019 Portfolio. All rights reserved | Design by
      <a href="#"> Nahid Hassan.</a>
    </p>
  </div>
</footer>
<!-- //footer -->
<!-- js -->

mysite/templates/include/head.html
{% load staticfiles %}
{% load static %}

<head>
  <link rel="shortcut icon" href="{% static 'android-icon-36x36.gif' %}" type="image/gif" sizes="16x16">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta charset="utf-8" />
  <meta name="keywords" content="Strive Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, 
  SmartPhone Compatible web template, free WebDesigns for Nokia, Samsung, LG, Sony Ericsson, Motorola web design" />
  <title>Nahid Hassan</title>
  <script>
    addEventListener("load", function () {
      setTimeout(hideURLbar, 0);
    }, false);

    function hideURLbar() {
      window.scrollTo(0, 1);
    }
  </script>
  <!-- Custom Theme files -->
  <link href="{% static 'css/bootstrap.css' %}" type="text/css" rel="stylesheet" media="all">
  <link href="{% static 'css/style.css' %}" type="text/css" rel="stylesheet" media="all">
  <!-- nav -->
  <link href="{% static 'css/menufullpage.css' %}" rel="stylesheet">
  <!-- font-awesome icons -->
  <link href="{% static 'css/fontawesome-all.min.css' %}" rel="stylesheet">
  <!-- //Custom Theme files -->
  <!-- online-fonts -->
  <link
    href="//fonts.googleapis.com/css?family=Fira+Sans+Condensed:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i"
    rel="stylesheet">
  <!-- //online-fonts -->
</head>

mysite/templates/include/top_nav.html
<header>
  <!--nav -->
  <a href="#menu" class="menu-link">
    <span>toggle menu</span>
  </a>
  <nav id="menu" class="panel">
    <ul>
      <li>
        <a href="{% url 'mysite:home' %}" class="active">Home</a>
      </li>
      <li>
        <a href="{% url 'mysite:about' %}">About</a>
      </li>
      <li>
        <a href="{% url 'mysite:skills' %}">Skills</a>
      </li>
      <li>
        <a href="{% url 'mysite:services' %}">Services</a>
      </li>
      <li>
        <a href="{% url 'mysite:portfolio' %}">Portofolio</a>
      </li>
      <li>
        <a href="{% url 'mysite:contact' %}">contact</a>
      </li>
    </ul>
  </nav>
  <!-- //nav -->
  <!-- logo -->
  <div class="logo_wthree">
    <a href="{% url 'mysite:home' %}">
      <i class="fas fa-code"></i>
    </a>
  </div>
  <!-- //logo -->
</header>

mysite/templates/index.html
<!--Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
{% load static %}
<!DOCTYPE html>
<html lang="zxx">

{% include "include/head.html" %}

<body>
    <!-- header -->
    {% include "include/top_nav.html" %}

    <!-- //header -->
    <!-- banner -->
    <section class="slide-wrapper">
        <!-- banner slide -->
        <div class="agile_banner bg1">
            <div class="layer">
                <div class="container">
                    <div class="banner_text_wthree">
                        <div class="d-flex">
                            <h1>welcome to </h1>
                            <h2>&nbsp;my site</h2>
                        </div>
                        <div id="text" class="banner_text_w3ls my-md-5 my-3"></div>
                        <ul class="list-inline bnr_list_w3">
                            <li class="list-inline-item">
                                <a class="btn  text-white  scroll" href=" {% url 'mysite:portfolio' %}">view my
                                    work </a>
                            </li>
                            <li class="list-inline-item">
                                <a class="btn  text-white bg-dark scroll" href="{% url 'mysite:contact' %}">contact
                                    me</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- //banner-->
    <!-- footer -->

    {% include "include/footer.html" %}

    <script src="{% static 'js/jquery-2.2.3.min.js' %}"></script>
    <!-- //js -->
    <!-- few java snippets-->
    <script src="{% static 'js/strive.js' %}"></script>
    <!-- banner text animation -->
    <script>
        //text effect

        document.addEventListener('DOMContentLoaded', function (event) {

            var dataText = [
                "Hi there, Iam  Nahid Hassan.",
                "I'm  a Computer Engineer.",
                "I have strong knowledge in competitive Programming",
                "As well as in Python, Java and other several language",
                "Web Development with Django and Flask"
            ];

            // type one text in the typwriter
            // keeps calling itself until the text is finished
            function typeWriter(text, i, fnCallback) {
                // chekc if text isn't finished yet
                if (i < (text.length)) {
                    // add next character to h1
                    document.getElementById("text").innerHTML = text.substring(0, i + 1) +
                        '<span aria-hidden="true" class="banner_text_w3ls"></span>';

                    // wait for a while and call this function again for next character
                    setTimeout(function () {
                        typeWriter(text, i + 1, fnCallback)
                    }, 70);
                }
                // text finished, call callback if there is a callback function
                else if (typeof fnCallback == 'function') {
                    // call callback after timeout
                    setTimeout(fnCallback, 1000);
                }
            }
            // start a typewriter animation for a text in the dataText array
            function StartTextAnimation(i) {
                // check if dataText[i] exists
                if (i < dataText[i].length) {
                    // text exists! start typewriter animation
                    typeWriter(dataText[i], 0, function () {
                        // after callback (and whole text has been animated), start next text
                        StartTextAnimation(i + 1);
                    });
                }
            }
            // start the text animation
            StartTextAnimation(0);
        });
    </script>

    <!-- //banner text animation -->
    <!-- nav -->
    <script src="{% static 'js/menuFullpage.min.js' %}"></script>
    <!-- //nav -->
    <!-- smooth scroll -->
    <script src="{% static 'js/SmoothScroll.min.js' %}"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/bootstrap.js' %}"></script>
</body>

</html>

mysite/templates/portfolio.html
<!--Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
{% load static %}
<!DOCTYPE html>
<html lang="zxx">

{% include "include/head.html" %}

<body>
    <!-- inner banner -->
    <div class="inner-banner-agile banner-port">
        <!-- header -->
        {% include "include/top_nav.html" %}
        <!-- //header -->
    </div>
    <!-- //inner banner -->
    <!-- gallery -->
    <section class="gallery pb-5">
        <div class="container">
            <div class="wthree-inner-sec port-bg">
                <div class="sec-head">
                    <h1 class="sec-title-w3 text-capitalize">portfolio</h1>
                    <span class="block"></span>
                </div>
                <!-- portfolio-area -->
                <div class="wthree-row py-3">

                    <ul class="portfolio-area clearfix">
                        {% for pro in projects %}
                        <li class="portfolio-item2" data-id="id-0" style="" >
                            <span class="image-block img-hover">

                                    <img src="{{ pro.thumbnail.url }}" class="img-fluid w3layouts agileits tor"
                                        alt="Communal">

                                <b style="text-align:center; "> <p style="color:green;">{{pro.title}}</p></b>
                            </span>
                            <p>{{ pro.description }} </p>
                            <br>
                            <p>Technology Use : <b>{{ pro.tech }}</b></p>
                            <br>
                            <p>
                                <a href="{{pro.github_link}}" target="_blank" class="clickme">Github Link</a>
                                {% if pro.live %}
                                <a href="{{pro.live}}" target="_blank" class="clickme info">Live Here</a>
                                {% endif %}
                            </p>
                        </li>
                      {% endfor %}
                    </ul>
                    <!--end portfolio-area -->
                </div>
            </div>
        </div>
    </section>
    <!-- //gallery -->
    <!-- footer -->
    {% include "include/footer.html" %}
    <!-- //footer -->
    <!-- js -->
    <script src="{% static 'js/jquery-2.2.3.min.js' %}"></script>
    <!-- //js -->
    <!-- few java snippets-->
    <script src="{% static 'js/strive.js' %}"></script>
    <!-- //few java snippets-->
    <!-- nav -->
    <script src="{% static 'js/menuFullpage.min.js' %}"></script>
    <!-- //nav -->
    <!-- smooth scroll -->
    <script src="{% static 'js/SmoothScroll.min.js' %}"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <!-- jQuery-Photo-filter-lightbox-Gallery-plugin -->
    <script src="{% static 'js/jquery-1.7.2.js' %}"></script>
    <script src="{% static 'js/jquery.quicksand.js' %}"></script>
    <script src="{% static 'js/script.js' %}"></script>
    <script src="{% static 'js/jquery.prettyPhoto.js' %}"></script>
    <!-- //jQuery-Photo-filter-lightbox-Gallery-plugin -->

</body>

</html>

mysite/templates/services.html
<!--Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
{% load static %}
<!DOCTYPE html>
<html lang="zxx">

{% include "include/head.html" %}

<body>
    <!-- inner banner -->
    <div class="inner-banner-agile services">
        <!-- header -->
        {% include "include/top_nav.html" %}
        <!-- //header -->
    </div>
    <!-- inner banner -->
    <!-- services -->
    <section class="pb-5">
        <div class="container">
            <div class="wthree-inner-sec services-bg">
                <div class="sec-head">
                    <h1 class="sec-title-w3 text-capitalize text-white">services</h1>
                    <span class="block"></span>
                </div>
                <section class="slide-wrapper">
                    <div class="services pt-5">
                        <div class="container">
                            <div class="row">
                                <div class="col-lg-4 my-auto">
                                    <img src="{% static 'images/code.png' %}" alt="" class="img-fluid" />
                                </div>
                                <div class="col-lg-4">
                                    <div class="d-flex services-box">
                                        <span class="icon">
                                            <i class="fas fa-pencil-alt"></i>
                                        </span>
                                        <!-- .Icon ends here -->
                                        <div class="service-content">
                                            <h2>Full Stack</h2>
                                            <p>
                                                I can build a powerful website with just traditional Django and also front end with Js library
                                            </p>
                                        </div>
                                        <!-- .Service-content ends here -->
                                    </div>
                                    <!-- .Services-box ends here -->

                                    <div class="d-flex services-box">
                                        <span class="icon">
                                            <i class="fas fa-rocket"></i>
                                        </span>
                                        <!-- .Icon ends here -->
                                        <div class="service-content">
                                            <h4>Deploying</h4>
                                            <p>
                                               I can Deploy your any Python site into Amazon EC2/AWS/Digital Ocean/Heroku
                                            </p>
                                        </div>
                                        <!-- .Service-content ends here -->
                                    </div>
                                    <!-- .Services-box ends here -->
                                    <div class="d-flex services-box">
                                        <span class="icon">

                                            <i class="fas fa-database"></i>
                                        </span>
                                        <!-- .Icon ends here -->
                                        <div class="service-content">
                                            <h4>Data Analysis</h4>
                                            <p>
                                               I am good at Data Analysis so if you need any kind of help for analysis your data that time I can give you the best solution.
                                            </p>
                                        </div>
                                        <!-- .Service-content ends here -->
                                    </div>
                                    <!-- .Services-box ends here -->

                                </div>
                                <!-- .Col ends here -->
                                <div class="col-lg-4">

                                    <!-- .Services-box ends here -->

                                    <div class="d-flex services-box">
                                        <span class="icon">
                                            <i class="fas fa-paint-brush"></i>
                                        </span>
                                        <!-- .Icon ends here -->
                                        <div class="service-content">
                                            <h4>Advanced Features</h4>
                                            <p>
                                                Handeling Database, Speed up website, Integrating different data source
                                            </p>
                                        </div>
                                        <!-- .Service-content ends here -->
                                    </div>
                                    <!-- .Services-box ends here -->
                                    <div class="d-flex services-box">
                                        <span class="icon">
                                            <i class="fas fa-code"></i>
                                        </span>
                                        <!-- .Icon ends here -->
                                        <div class="service-content">
                                            <h4>Clean Design</h4>
                                            <p>
                                                I can help you to Desing your  website for best performance.
                                            </p>
                                        </div>
                                        <!-- .Service-content ends here -->
                                    </div>
                                    <!-- .Services-box ends here -->
                                </div>
                                <!-- .Col ends here -->
                            </div>
                            <!-- .Row ends here -->
                        </div>
                        <!-- .Container ends here -->
                    </div>
                    <!-- .Services ends here -->
                </section>
            </div>
        </div>

    </section>
    <!-- //services -->
    <!-- footer -->
    {% include "include/footer.html" %}
    <!-- //footer -->
    <!-- js -->
    <script src="{% static 'js/jquery-2.2.3.min.js' %}"></script>
    <!-- //js -->
    <!-- few java snippets-->
    <script src="{% static 'js/strive.js' %}"></script>
    <!-- //few java snippets-->
    <!-- nav -->
    <script src="{% static 'js/menuFullpage.min.js' %}"></script>
    <!-- //nav -->
    <!-- smooth scroll -->
    <script src="{% static 'js/SmoothScroll.min.js' %}"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/bootstrap.js' %}"></script>

</body>

</html>

mysite/templates/skills.html
<!--Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
{% load static %}
<!DOCTYPE html>
<html lang="zxx">

{% include "include/head.html" %}

<body>
    <!-- inner banner -->
    <div class="inner-banner-agile skillset">
        <!-- header -->
        {% include "include/top_nav.html" %}
        <!-- //header -->
    </div>
    <!-- inner banner -->
    <!-- skill set -->
    <section class="pb-5">
        <div class="container">
            <div class="wthree-inner-sec skills-bg">
                <div class="sec-head text-center">
                    <h1 class="sec-title-w3 text-capitalize text-dark">skill set</h1>
                    <span class="block mx-auto"></span>
                </div>
                <div class="wthree-row py-md-5 py-3">
                    <div id="wrapper">
                        <div class="chart">
                            <table id="data-table" class="table-responsive">
                                <thead>
                                    <tr>
                                        <th scope="col">Full Stack</th>
                                        <th scope="col">ML</th>
                                        <th scope="col">Python</th>
                                        <th scope="col">Java</th>
                                        <th scope="col">PHP</th>


                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td>90</td>
                                        <td>50</td>
                                        <td>95</td>
                                        <td>90</td>
                                        <td>80</td>


                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- //skill set -->
    <!-- footer -->
    {% include "include/footer.html" %}
    <!-- //footer -->
    <!-- js -->
    <script src="{% static 'js/jquery-2.2.3.min.js' %}"></script>
    <!-- //js -->
    <!-- few java snippets-->
    <script src="{% static 'js/strive.js' %}"></script>
    <!-- //few java snippets-->
    <!-- nav -->
    <script src="{% static 'js/menuFullpage.min.js' %}"></script>
    <!-- //nav -->
    <!-- smooth scroll -->
    <script src="{% static 'js/SmoothScroll.min.js' %}"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/skill.js' %}"></script>
</body>

</html>